=== lvscan
Modificar y gestionar volúmenes lógicos en LV, incluyendo opciones para listar, crear, borrar y cambiar tipos de volúmenes lógicos, así como mostrar información detallada y filtrar resultados según criterios específicos.

:category: local_storage
[.metadata]
{
  "description": "Modificar y gestionar volúmenes lógicos en LVM.",
  "usage": "lvscan [OPCIONES]",
  "options": {
    "-l": "Listar volúmenes lógicos",
    "-t": "Cambiar tipo de volumen lógico (modo interactivo)",
    "-n": "Crear nuevo volumen lógico (modo interactivo)",
    "-d": "Borrar un volumen lógico (modo interactivo)",
    "-p": "Mostrar información de un volumen lógico (modo interactivo)",
    "-a": "Incluir volúmenes inactivos o internos",
    "--cache": "Usar caché de LVM para acelerar el escaneo",
    "-v": "Modo verbose para mostrar detalles adicionales",
    "--ignorelockingfailure": "Ignorar errores de bloqueo de dispositivos"
  }
}

[source,bash]
----
# Escanear todos los volúmenes lógicos del sistema
lvscan
----

-a:: `lvscan -a` Incluir volúmenes inactivos o internos

[source,bash]
----
# Mostrar todos los LV, incluso los no activos
lvscan -a
----

--cache:: `lvscan --cache` Usar caché de LVM para acelerar el escaneo

[source,bash]
----
# Escanear LV usando información en caché
lvscan --cache
----

-v:: `lvscan -v` Modo verbose para mostrar detalles adicionales

[source,bash]
----
# Escanear LV mostrando información detallada
lvscan -v
----

--ignorelockingfailure:: `lvscan --ignorelockingfailure` Ignorar errores de bloqueo de dispositivos

[source,bash]
----
# Escanear LV aunque haya errores de bloqueo
lvscan --ignorelockingfailure
----

